# These are supported funding model platforms

github: # Replace with your GitHub username
# patreon: # Replace with your Patreon username
# open_collective: # Replace if you have one
# ko_fi: # Replace
# liberapay: # Replace
# custom: ['https://your-donation-link.com']
